### ISSUE TITLE
Automated parameter set for BP and EAMD

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#18]
Now, we have to manually provide the parameters for BP and EAMD. It would be nice to have a simple utility to generate a default set.

**Comment by yanxon** [comment]
@qzhu2017 

This is a challenging task to do. I truly believe the accuracy you obtain with the different parameter sets depends on the dataset.

There are multiple studies on automated parameters for BP/EAD. Here are some that I found in the literature:
1. https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.9b02037
2. https://aip.scitation.org/doi/10.1063/1.5019667

I used these methods for SiO2 dataset. However, none of them beats the accuracy provided by Simple-NN.

**Comment by qzhu2017** [comment]
@yanxon 
It is better than nothing.
