### ISSUE TITLE
GPU version based on the big array 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#22]
@yanxon 
Here is a short summary regarding our discussion today.
elements = ["Si", "O"]
-struc1, SiO2
x: [N1, L]                    + x[N2, L]         -> [N1+N2, L]
rdxdr: [N1, L, 6]
map-x: [N1, 2]           + map_x[N2, 2].  -> [N1+N2, 2]
[0,0,0,0,..........; -> structure id
 0,0,0,1,1,1,1,1,; ->  type_id,
 4,4, ...............-> NN
]

"""PyXtal_FF/pyxtal_ff/utilities/__init__.py"""

## database:
x: [N1, L]   + x[N2, L]   + ....      -> [N1+N2+..., L]
rdxdr: [N1, L, 6] + [N2, L, 6] + ... > [N1+N2+..., L, 6]
map_x: [N1, 3]   + map_x[N2, 3] + ......  -> [N1+N2+...., 2] #[structure_id, type_id]

dxdr: [NN1, L, 3] + dxdr: [NN2, L, 3]  + .....  ->  [NN1+NN2+..., L, 3]
map_dxdr: [NN1, 2] + map-dxdr[NN2, 2] + ..... -> [NN1+NN2+..., 2]

energy: [N]
force: [N1+N2+...., 3]
stress: [N, 6]
                                          
                      

## NN->Preprocess:

```python
_drange={}

for i, ele in enumerate(elements):     # ["Si", "O"]):
    ids = np.where(map_x[:,1]==i)[0]
    _x[ele] = x[ids]     -> [N_Si, L]
    min_x = np.min(_x[ele])        -> [L]
    max_x = np.max(_x[ele])       -> [L]
    drange[ele] = [min_x; max_x] -> [L, 2]
```

### NN pick_batch-> class Dataset(data.Dataset):

batch_structure_ids
1000 structures
50 minibatch
pytorch data loader generates 20 lists of batch_structure_ids with a length of 50.

```python

# with bumpy
for _id in batch_structure_ids: [17, 49]
    ids = np.where(map_x[:,0]==_id)[0]
    batch_x.append(x[ids])
    batch_rdxdr.append(rdxdr[ids])
    id_start = np.where(map_dxdr[:,0]==ids[0]) [0][0]
    id_end = np.where(map_dxdr[:,0]==ids[-1]) [0][-1]
    tmp = dxdr[id_start: id_end]
    batch_dxdr.append(tmp)        [333, 334, 335] -> [0,1,2]
    batch_map_x =.   # compute total energy/stress, -> 0,1,2,3,4 [structure_id, atom_id]
    batch_map_dxdr =. # compute force -> 0,1,2,3,4,5
    batch_energy = 
    batch_stress =
    batch_force.append(force[ids])

# copy this to cuda
    batch_dxdr.append(tmp).to(self.device)     
    batch_map_x =.   
    batch_map_dxdr =. 
    batch_energy = 
    batch_stress =
    batch_force = 
```

### NN_calculate_loss

```python
energy = zeros(batch_size)
stress = zeros(batch_size, 6)
force = zeros(len(batch_x), 3)
for i, ele in enumerate(elements):     # ["Si", "O"]):
#for element, model in models.items():                   
    ids = np.where(map_x[:,1]==i)[0]
    _x[ele] = x[ids]     #-> [N_Si, L]
    _rdxdr[ele] =  rdxdr[ids] #-> [N_Si, L, 6]
                      
    # to extract dxdr needs some tunning
    for id in ids:
        _dxdr[ele] = np.append(_dxdr[ele], dxdr[map_dxdr[ids,0]==id])
    
    # apply normalization
                      
    # compte E/F/S                      
    _energy = model[ele](_x[ele])
    dedxs = np.zeros([N_atoms, N_descriptors])
    for i in range(batch_size):
        E = _energy[id_start:id_end].sum()
        energy[i] += E
        dedxs[id_start:id_end] = torch.autograd.grad(_energy, _x, create_graph=True)[0]                    
    
   # If this is too big, we may split them to several subsets
    tmp = torch.zeros([len(x[ele]), n_atoms, x[ele].shape[1], 3])
    for _m in range(n_atoms):
        ids = np.where(map_dxdr[ele][:,1]==_m)[0]
        tmp[map_dxdr[ele][ids, 0], _m, :, :] += dxdr[ele][ids, :, :]
                      
    _force -= torch.einsum("ik, ijkl->jl", dedx[element], tmp) # [N, L] [N, L, 3] -> 3
                                            
    stresses += torch.einsum("ik, ikl->il", -dedxs, rdxdr[ele]) # [N_atoms, 6]                       
    for i in range(batch_size):
        stress[i] = stresses[id_start:id_end].sum()
                      
```

**Comment by qzhu2017** [comment]
@yanxon 
I think most of them can be also merged to the CPU version. The only issue is that we may need to do several einsums for the force calculation if we do the full batch.

I suggest you implement this in the 3d-dxdr branch. I just updated this to the master branch.

**Comment by yanxon** [comment]
@qzhu2017 

To make life easier, I believe we need to add another column on `dxdr_map` for structure identification. For example, let's assume we have 2 structures. Structure 1 and 2 have 2 atoms each. While assuming we cover enough Rc, `dxdr_map` becomes:
```
0, 0, 0
0, 0, 1
0. 1, 0
0, 1, 1

1, 0, 0
1, 0, 1
1, 1, 0
1, 1, 1
```
The first column identifies the structure, second column is the i-th pair, and third column is the j-th pair.

**Comment by qzhu2017** [comment]
@yanxon Please put your thoughts regarding one einsum to compute the force here.

**Comment by yanxon** [comment]
@qzhu2017 

Sorry, I thought about it more, one einsum to compute force won't work because it's very memory consuming.

Here is my thought regarding one einsum to compute force:
```
dEdX -> [N1+N2..., L]
dXdR -> [N1_ij+N2_ij..., L, 3]
dEdX_dXdR = torch.einsum('ij,kjl->ikjl', dEdX, dXdR)            #[N1+N2..., N1_ij+N2_ij..., L, 3]

for struc in structures:
    for j in num_atoms_in_struc:
        force[slice] = dEdX_dXdR[slice]
```

This means that we also compute dEdX_dXdR for structure N1 and N2_ij, which is not necessary.

Although I'm sure this will work, we compute unnecessary stuffs. I believe the original multiple einsum for loop works better.

**Comment by qzhu2017** [comment]
Maybe there is a clever way to change 
dEdX from the size [N1+N2..., L] -> [N1_ij+N2_ij..., L]
Then you do 
dEdX_dXdR = torch.einsum('ij,ijk->ijk', dEdX, dXdR). #[N1_ij+N2_ij..., L, 3]
Now you change it to [N1+N2..., L, 3], and then [N1+N2..., 3]
I can tell you more details.

**Comment by yanxon** [comment]
@qzhu2017 

This is inspiring!
I think this will work, we will just broadcast the same dEdX correspondingly since we have `dxdr_map`.

**Comment by yanxon** [comment]
@qzhu2017 @David-Zagaceta 

Issue in indexing/slicing in torch tensor:
https://github.com/pytorch/pytorch/issues/29973

**Comment by yanxon** [comment]
@qzhu2017 

It seems like I can't make one einsum for force working. 

Here is a simplified code. Let's say we have 2 structures (3 atoms and 2 atoms each) with 5 descriptors. Hence, we have `x.shape = [5, 5]`
```
  1 import torch
  2 from torch.autograd import grad
  3 
  4 x = torch.ones(5,5, dtype=torch.float, requires_grad=True)
  5 w = torch.rand(5,5, dtype=torch.float, requires_grad=True)
  6 atomic_energies=torch.sum(x*w, dim=1)
  7 
  8 energy1=atomic_energies[0:3].sum()
  9 dedx_struc1 = grad(energy1, x[0:3,:], create_graph=True)
```

This will give error as such:
```RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.```

Here is a solution:
https://discuss.pytorch.org/t/how-to-calculate-gradients-wrt-one-of-inputs/24407
However, this solution is what we have originally!
