### ISSUE TITLE
Cutoff functions

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#27]
@yanxon 

You need to make sure that the newly added cutoff functions (2255b55eaecc39426b76c9c651d1ed4170f21fa5) can be called in someway.
Also, please update the documentation in the following places

https://pyxtal-ff.readthedocs.io/en/latest/_rsts/links/_background.html#atomic-descriptors
https://pyxtal-ff.readthedocs.io/en/latest/_rsts/links/_quickstart.html

This will be one of the improvements for v.0.1.2

**Comment by yanxon** [comment]
@qzhu2017 

Now the cutoff function can be called in this fashion:
```
descriptor = {'type': 'BehlerParrinello',
              'parameters': symmetry,
              'Rc': 5.0,
              'ncpu': 4,
              'cutoff': 'cosine'}
```
