### ISSUE TITLE
.traj format doesn't work

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_FF#28]
From Fuzhu (Xi'an Jiaotong University):

But I have written a function to read my .traj file, that already works. If you try to run my python scripts, you should update the __init__.py file (see the attachment) in the path of "lib/python3.8/site-packages/pyxtal_ff/utilies/__init__.py". This will not influence the reading of other file types (json, xyz, vasp-out). I just added a new format (.traj).

I think the new file-type .traj can keep in the new version of pyxtal_ff, because the data with the .traj file is used in the Amp package.
```
def parse_traj(structure_file):
    data = []
    out_traj = read(structure_file,':')
    for traj in out_traj:
        atoms_symbol = traj.symbols
        positions = traj.positions
        cell = traj.cell
        structure = Atoms(symbols = atoms_symbol,
            positions = positions,
            cell = cell,
            pbc = True)
        energy = traj.get_potential_energy()
        force = traj.get_forces()
        xjson = {'structure':structure,
        'energy':energy,
        'force':force,
        'stress':None,
        'group':'random'}
        data.append(xjson)
    #print (len(data))
    return data
```

Issue:
1. I assumed the package works for several elements existed systems. Run the < run_ase_pyxtal_NN.py >,  RuntimeError: The size of tensor a (55) must match the size of tensor b (63) at non-singleton dimension 0.

2. The linear regression model works on the training.traj data, and the potential was successfully created. (just run < run_ase_pyxtal_PR.py >), but when using the Potential through ase calculator, the error is "NotImplementedError: ACSF is not implemented", seemly the descriptor was not calculated.

**Comment by qzhu2017** [comment]
@yanxon 
can you add the `parse_traj` to our code?

**Comment by yanxon** [comment]
@qzhu2017 

`parse_traj` has been added in 3e07645062adccddfbc46950ff0d52f6f7bbdc2e.

**Comment by FuzhuLiu** [comment]
@yanxon yes, I see, thanks.
