### ISSUE TITLE
Debug the SNAP option

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#34]
- [x] added a test dxdr function to SNAP
- [x] make sure that dxdr is consistent with the numerical derivatives. 
The problem is due to mis-accumulation of dxdr when i==j

**Comment by yanxon** [comment]
@qzhu2017 @David-Zagaceta 
It seems like test function for SNAP is working properly.

**Comment by qzhu2017** [comment]
@David-Zagaceta @yanxon 
Let's discuss this in our afternoon meeting. Would you like to start the meeting earlier (e.g 2:30)?

**Comment by yanxon** [comment]
@qzhu2017 
2:30 should be ok.

**Comment by David-Zagaceta** [comment]
@qzhu2017 2:30 works for me

**Comment by qzhu2017** [comment]
@David-Zagaceta @yanxon 
https://unlv.webex.com/unlv-en/j.php?MTID=mbc45b5b6f55603de79005fba8536d41f

**Comment by yanxon** [comment]
@qzhu2017 @David-Zagaceta 
I just fixed `SNAP.py` (32e25b1b399843d22b912488e725839e6541b077). This is consistent with LAMMPS output now.

@David-Zagaceta, do you think you should do the same with `SO4` and `SO3`?

**Comment by qzhu2017** [comment]
@David-Zagaceta I believe this needs to be fixed in both SO4 and SO3. Please let me know when you fix them.
