### ISSUE TITLE
Wigner Coeffs

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#36]
@macstein
lammps use a running folder as current folder. For example, if I run "../../src/lmp_serial < in.Mo" in "../exmaples/mliap" folder, "../examples/mliap" is current folder. So I have to leave "Wigner_coefficients.dat" in the "../exmaples/mliap" folder (current folder). 
In this case, a user should keep "Wigner_coefficients.dat" in their running folder. 
Now, I don't find any solution to resolve this issue.
We may put "Wigner_coefficients.dat" in the source code itself, it is way big though.
Do you have any idea?

@David-Zagaceta In our python code, we computed L up to 32. However, we mostly used l=4-8 for the realistic computation. Can we just write down the numbers in the cpp file, instead of extract the numbers from a dat file?

**Comment by qzhu2017** [comment]
Sounds good. It is better to avoid some extra files

**Comment by qzhu2017** [comment]
@macstein 

@David-Zagaceta just make a commit to compute the coefficient on the fly. You can do the same thing in the cpp code. It should be some easy change.

**Comment by macstein** [comment]
@qzhu2017 I implemented computing the coefficient code in the cpp code and tested.
