### ISSUE TITLE
Add the cutoff function to SO3

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_FF#39]
@David-Zagaceta 
@macstein 

Currently, the SO3 suffers from the numerical instability when the distances are right at the cutoff. To fix it, we can add a cutoff function to force the decay of descriptor.

Let's try it after the work on SPH.

**Comment by macstein** [comment]
@qzhu2017 
I am ready to test cutoff function in lammps SO3 C++. Descriptors are agree with @David-Zagaceta 's new so3.py. I need to check dxdr. Can I have a trained data (coefficient) and results (energy, forces) for Si or Ni_Mo using @David-Zagaceta 's new so3.py?  

Fortunately, in my test, adding radial cutoff functions to current lammps SO3 c++ does not slow down the speed. For 8000 Si atoms and 10 runs, it takes 36 sec now on my laptop. It took 35 sec before adding the radial cutoff functions. I will double check it, once I finalize this adding.

**Comment by qzhu2017** [comment]
@macstein 
Let's do it after @David-Zagaceta implemented the new way to compute SO3.

**Comment by macstein** [comment]
@David-Zagaceta 
I am having inconsistent descriptor. Let me go with simple sample Mo _**without rcut function**_ first.
I am using Mo.poscar and lmax=3, nmax=3, rcut=3.5, and alpha=2.0
```
bcc Mo
1.0
3.167618 0.0 0.0
0.0 3.167618 0.0
0.0 0.0 3.167618
Mo
2
Cart
0.0  0.0  0.0
1.583809  1.583809  1.583809

```
In SO3.c++, I set up compute_sfac and compute_dsfac to return 1.0 for all cases. Then I have below.
(1)
```
x
1.02932e+04 , 1.72827e-29 , 5.08039e-29 , 8.88750e-29 , 
-9.03850e+03 , 3.10397e-30 , -3.60924e-29 , -7.56429e-29 , 
7.93675e+03 , 2.71605e-29 , 2.70561e-29 , 7.12131e-29 , 
2.03298e+03 , 2.47819e-31 , 9.80154e-30 , 2.30130e-29 , 
-1.78517e+03 , -6.32740e-30 , -6.88355e-30 , -1.79181e-29 , 
4.01529e+02 , 1.60461e-30 , 2.01852e-30 , 6.49587e-30 , 

1.02932e+04 , 3.51078e-28 , 5.63464e-29 , 2.35541e-28 , 
-9.03850e+03 , -5.06888e-28 , -3.88658e-29 , -2.51836e-28 , 
7.93675e+03 , 7.63368e-28 , 2.79788e-29 , 2.85686e-28 , 
2.03298e+03 , 1.04969e-28 , 9.78537e-30 , 4.63618e-29 , 
-1.78517e+03 , -1.55304e-28 , -7.10118e-30 , -5.05627e-29 , 
4.01529e+02 , 3.18386e-29 , 1.87572e-30 , 9.67313e-30 ,
```
In previous SO3.py (before einsum, probably weeks ago),  I also set up compute_sfac and compute_dsfac to return 1.0 for all cases. Then I have below.
(2)
```
x [[ 1.02931931e+04  6.47522189e-29  1.38365407e-28  7.28848143e-29
  -9.03850248e+03 -3.23761094e-29 -1.26529818e-28 -6.14328977e-29
   7.93675255e+03  1.82115616e-29  1.22792673e-28  5.37329893e-29
   2.03298104e+03  1.21410410e-29  2.95657124e-29  2.00693649e-29
  -1.78517045e+03 -7.08227394e-30 -2.89318809e-29 -1.73452065e-29
   4.01528648e+02  2.90879108e-30  6.94954061e-30  6.04120190e-30]
 [ 1.02931931e+04  9.28922179e-28  1.52087097e-28  3.32286028e-28
  -9.03850248e+03 -8.22043360e-28 -1.41636863e-28 -3.72622243e-28
   7.93675255e+03  7.28828843e-28  1.45455083e-28  4.31592524e-28
   2.03298104e+03  2.34416602e-28  2.57132195e-29  9.65566869e-29
  -1.78517045e+03 -2.07696323e-28 -2.67964429e-29 -1.10361498e-28
   4.01528648e+02  5.92535619e-29  5.24755705e-30  2.85297152e-29]]

```
In the latest SO3.py, I set cutoff_array as 1.0, so in case of Mo, it is like that
```
in compute_cs
cutoff_array [0.1109837  0.02208792 0.02208792 0.02208792 0.02208792 0.02208792
 0.02208792 0.1109837  0.1109837  0.1109837  0.1109837  0.1109837
 0.1109837  0.1109837  0.1109837  0.02208792 0.1109837  0.02208792
 0.1109837  0.1109837  0.02208792 0.1109837  0.1109837  0.1109837
 0.1109837  0.02208792 0.02208792 0.02208792]
cutoff_array after [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
```
Then I have below.
(3)
```
x [[ 1.15839122e+03  1.77493704e-30  6.06737528e-30  9.86076132e-30
  -1.01718891e+03  0.00000000e+00 -4.35178203e-30 -5.71924156e-30
   8.93198478e+02  0.00000000e+00  4.37761570e-30  7.49417860e-30
   2.28790751e+02 -1.97215226e-31  9.86092387e-31  1.52841800e-30
  -2.00902260e+02  0.00000000e+00 -8.30746503e-31 -1.49144015e-30
   4.51878492e+01  2.46519033e-32  1.74083882e-31  4.40652771e-31]
 [ 1.15839122e+03  9.44313204e-29  6.21317205e-30  8.59270334e-29
  -1.01718891e+03 -8.23340073e-29 -3.78102587e-30 -8.85446978e-29
   8.93198478e+02  7.84278665e-29  7.20331948e-30  9.75810495e-29
   2.28790751e+02  1.64947902e-29  1.04945426e-30  2.34369410e-29
  -2.00902260e+02 -1.57146042e-29 -1.05348515e-30 -2.53591322e-29
   4.51878492e+01  3.15425774e-30  2.15806039e-31  6.79223998e-30]]

```
(1) and (2) are the same, however (3) is not. 
In case of (3), is "I set cutoff_array as 1.0" correct way to remove rcutoff function?
If it is not, please let me know how to ignore the rcutoff function.
If it is correct, can you please double check if the latest SO3.py has consistent descriptor with old SO3.py?

**Comment by David-Zagaceta** [comment]
@macstein I removed the cutoff function by setting sfac to 1.0 and dsfac to 0.0

**Comment by David-Zagaceta** [comment]
Can you also give that file to me in POSCAR format?

**Comment by macstein** [comment]
@David-Zagaceta 
Here is the Mo.poscar
```
bcc Mo
1.0
3.167618 0.0 0.0
0.0 3.167618 0.0
0.0 0.0 3.167618
Mo
2
Cart
0.0  0.0  0.0
1.583809  1.583809  1.583809
```

**Comment by David-Zagaceta** [comment]
@macstein I got the file, I'm looking into differences now because I had same descriptor for a different structure.

**Comment by David-Zagaceta** [comment]
@macstein Your weight is the atomic number of Mo here as well right?

**Comment by macstein** [comment]
@David-Zagaceta Yes.

**Comment by qzhu2017** [comment]
@David-Zagaceta Have you figured out what the discrepancy comes from? We need to get it done asap.

**Comment by macstein** [comment]
@David-Zagaceta 
Now x is consistent with/without cutoff function.
When I use cutoff function, dxdr should be consistent, right?

dxdr are not same. I think I have a bug in SO3.c++. However, it is hard to compare because of different dimension of dxdr array.
In Mo case,
SO3.py
```
dxdr dim[ 4, 24, 3]
dxdr [[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 8.50893519e-15  0.00000000e+00  0.00000000e+00]
  [-2.41588652e-30 -1.97215226e-31 -7.88860905e-31]
  [-3.15662168e-15  0.00000000e+00  0.00000000e+00]
...
```
SO3.c++
```
dxdr[npairs=28, ndescript=24,3]

dxdr
[[[0.00000e+00 0.00000e+00 1.33088e+01 ]
  [5.98459e-18 1.62484e-17 8.33001e-16 ]
  [-3.88396e-18 -2.46141e-17 -2.68558e-17 ]
...
``` 
Is there any way I can print dxdr[npairs,ndescript,3] in SO3.py ?

**Comment by David-Zagaceta** [comment]
I will write a script that can output it in that format

**Comment by David-Zagaceta** [comment]
dXdr should be consistent though in my version.  It agrees with the
numerical gradient.

**Comment by macstein** [comment]
@qzhu2017 I just remembered that I have checked SO3.c++ x with SO3.py and dxdr with energy and forces from PyXtal_FF (not directly using SO3.py for dxdr).  
Can I have trained data (coefficient) and result (energy, forces) for Si , Mo and  Ni_Mo using @David-Zagaceta 's latest SO3.py applying cosine cutoff function?

**Comment by qzhu2017** [comment]
@David-Zagaceta Can you reply to @macstein's question? We need to get it done asap.

**Comment by David-Zagaceta** [comment]
@qzhu2017 I fixed stress

@macstein to get the output format you need with (npairs, ncoefs, 3) just add the line

`print(dP)`

to line 234

As far as the trained data do you just need me to upload the .db?


![image](https://user-images.githubusercontent.com/31450165/118727184-3afe3a00-b7e7-11eb-849e-0af63918e591.png)

**Comment by macstein** [comment]
@David-Zagaceta 
For the above Mo case, adding print('dP',len(dP),len(dP[0]),len(dP[0][0]),len(dP[0][0][0]),len(dP[0][0][0][0]))to line 234 prints 
```
dP 14 3 3 4 3
dP 14 3 3 4 3

```
In SO3.c++ dimension is dxdr[npairs=28, ndescript=24,3]
How can I convert dP to format of dxdr[npairs=28, ndescript=24,3]?

I will be need trained data once I implement rcut function in lammps.

**Comment by David-Zagaceta** [comment]
@macstein try

'print(dP.reshape(dP.shape[0], ncoefs, 3))'

**Comment by David-Zagaceta** [comment]
you will see conjugates or repeated values because of the symmetry but that should have the values you need

**Comment by macstein** [comment]
@David-Zagaceta 
I got an error.
```
  File "SO3.py", line 740, in <module>
    x = f.calculate(test)
  File "SO3.py", line 238, in calculate
    print(dP.reshape(dP.shape[0], ncoefs, 3))
ValueError: cannot reshape array of size 1512 into shape (14,24,3)

```

**Comment by David-Zagaceta** [comment]
@macstein That only worked for n=1, I realize that now.  Here's the final line

`print(dP[:,tril_indices[0], tril_indices[1], :,:].reshape(dP.shape[0], ncoefs, 3))`

**Comment by macstein** [comment]
@David-Zagaceta Although printing orders are not same, the dxdr values are consistent. Thank you!
@qzhu2017
Do we go with cosine rcut function?
If it is, I will let you know after implement (move) cosine rcut function into mliap_so3 branch. Meanwhile, I will need trained data with new SO3.py using cosine rcut function to check mliap_so3. Can I have the energy and forces for Mo and Ni_Mo?

**Comment by David-Zagaceta** [comment]
@macstein Do you just need coefficients for a LR and the a few specific structures from Mo and Ni_Mo?

**Comment by macstein** [comment]
@David-Zagaceta Yes I need coefficients with LR for Mo and Ni_Mo. And I need energy and forces for some Mo and Ni_Mo structure using PyXtal_FF. I will compare the forces and energy for the same structure using mliap_so3.

**Comment by qzhu2017** [comment]
@macstein If the results are consistent, I suggest you update your lammps code as well.

**Comment by macstein** [comment]
@qzhu2017 The results are consistent. I updated the mliap_so3 branch. I need trained data ( coefficients, energy, forces ) for the final check.

**Comment by qzhu2017** [comment]
@David-Zagaceta @macstein 
I just tested the case for [SiO2](https://github.com/qzhu2017/PyXtal_FF/tree/master/examples/SiO2-LAMMPS)

I believe the code now works for all cases now.
