### ISSUE TITLE
couldn't include stress in the training

### ISSUE THREAD

**Issue by weilaigit** [qzhu2017/PyXtal_FF#48]
I am using version 0.1.8 and it worked without including the stress in training.

I converted the vasprun.xml to a ASE trajectory file and used following settings:

from pyxtal_ff import PyXtal_FF
import os

TrainData = "./training.traj"

descriptor = {'type': 'SO3',
              'Rc': 6.0,
              'parameters': {'lmax': 4, 'nmax': 3},
              'ncpu': 1,
              'N_train': 1,
             }

model = {'system' : ['Si'],
         'hiddenlayers': [30, 30],
         'path': 'Si-so3/',
         #'restart': 'Si-so3/30-30-checkpoint.pth',
         'optimizer': {'method': 'lbfgs', 'lr': 5e-4},
         'force_coefficient': 0.1,
         'stress_coefficient': 2e-3,
         'stress_group': ['Elastic'],
         'epoch': 100,
         }

ff = PyXtal_FF(descriptors=descriptor, model=model)
ff.run(mode='train', TrainData=TrainData)

Here is the error I am getting:
Traceback (most recent call last):
  File "so3_train.py", line 27, in <module>
    ff.run(mode='train', TrainData=TrainData)
  File "/mnt/home/laiwei/.local/lib/python3.7/site-packages/pyxtal_ff/__init__.py", line 287, in run
    self.model.train('Train_db', optimizer=self.optimizer)
  File "/mnt/home/laiwei/.local/lib/python3.7/site-packages/pyxtal_ff/models/neuralnetwork.py", line 238, in train
    self.optimizer.step(closure)
  File "/mnt/home/laiwei/.local/lib/python3.7/site-packages/pyxtal_ff/models/optimizers/lbfgs.py", line 307, in step
    orig_loss = closure()
  File "/mnt/home/laiwei/.local/lib/python3.7/site-packages/pyxtal_ff/models/neuralnetwork.py", line 232, in closure
    train_loss, E_mae, F_mae, S_mae = self.calculate_loss(self.models, self.data)
  File "/mnt/home/laiwei/.local/lib/python3.7/site-packages/pyxtal_ff/models/neuralnetwork.py", line 531, in calculate_loss
    stress_loss = stress_loss / (2. * s_count)
ZeroDivisionError: float division by zero

I am not sure what are the meanings of different stress_groups (e.g. Elastic) but it appears that cell stress values are in the training.traj.

**Comment by yanxon** [comment]
@weilaigit, thank you for raising the concern and sorry for the late reply. For some reason, I didn't get any notification on this issue. For next time, you can tag my name @yanxon. I will respond quicker :)

The error shows that there is no stress being registered since the `group` is `Elastic`. Therefore, `s_count` is zero.

I just updated the traj code in f4a32b2589d54eecf69bb3fab0b6b0368b3db362.
1.  As long as, your trajectories have stress information. This should work.
2. Remove the `stress_group` option. You won't need this.

Please let me know if this works for you. If you have any other concerns, I will be more than happy to help.

**Comment by weilaigit** [comment]
@yanxon Thanks for the change and it worked (I removed the stress_group option).  However, the R-squared of stress looks bad and I am guessing there might be a unit issue (true stresses are between -0.05 and 0.05 GPa while predicted stresses are -3 to 3 GPa from the plot). 

The results for energy:
    Energy R2     0.858996
    Energy MAE    0.007898
    Energy RMSE   0.009947
The energy figure is exported to: Si-so3/Energy_Train.png

The results for force:
    Force R2      0.945403
    Force MAE     0.198455
    Force RMSE    0.249057
The force figure is exported to: Si-so3/Force_Train.png

The results for stress:
    Stress R2      -4415.628361
    Stress MAE     0.761415
    Stress RMSE    0.971014
The stress figure is exported to: Si-so3/Stress_Train.png

**Comment by yanxon** [comment]
@weilaigit, I wonder what is the unit of stress in your trajectory file. 

Is it eV/A^3? Can you please verify?

I am using `get_stress()` method to collect the stress:
https://wiki.fysik.dtu.dk/ase/_modules/ase/atoms.html#Atoms.get_stress

**Comment by weilaigit** [comment]
@yanxon Yes, the unit of stress is eV/A^3 as the trajectory is from ASE.  I tried to add the conversion factor (eV2Gpa=160.21766) in the get_stress() but the Rsquared of stress is still not very good.

The results for energy:
    Energy R2     0.856972
    Energy MAE    0.009647
    Energy RMSE   0.012666
The energy figure is exported to: Si-so3/Energy_Train.png


The results for force:
    Force R2      0.934688
    Force MAE     0.221715
    Force RMSE    0.278289
The force figure is exported to: Si-so3/Force_Train.png


The results for stress:
    Stress R2      -0.033134
    Stress MAE     1.933286
    Stress RMSE    2.441466
The stress figure is exported to: Si-so3/Stress_Train.png

**Comment by yanxon** [comment]
@weilaigit, in the Si-so3 folder, you can check `TrainStress.txt`. 

If you convert `Predicted` value through eV/A^3-GPa conversion. Can you get close to the `True` value?

**Comment by yanxon** [comment]
@weilaigit, I just changed the ASE traj stress from eV/A^3 to GPa internally so that it has unit consistency during the training (66079748157fa425a4ce5bc9e5e09924e35ed105). 

Can you please retry the training again? I'm curious to see the results :)

**Comment by weilaigit** [comment]
@yanxon This change is basically the same as multiplying the get_stress() by the conversion factor.  As a result, the training results are similar (the following).

==================== Evaluating Training Set ====================

The results for energy:
    Energy R2     0.859250
    Energy MAE    0.009693
    Energy RMSE   0.012564
The energy figure is exported to: Si-so3/Energy_Train.png


The results for force:
    Force R2      0.935574
    Force MAE     0.220712
    Force RMSE    0.276396
The force figure is exported to: Si-so3/Force_Train.png


The results for stress:
    Stress R2      -0.050751
    Stress MAE     1.947115
    Stress RMSE    2.462194
The stress figure is exported to: Si-so3/Stress_Train.png


Results of TrainStress.txt:

# Predicted True Diff
4.0815753e+00 -2.5874716e+00 6.6690470e+00
2.3998713e+00 -4.8001182e+00 7.1999894e+00
-2.1441449e+00 2.8147098e+00 4.9588547e+00
1.1007487e+00 -1.1494885e+00 2.2502372e+00
6.4598191e-02 -1.5434162e+00 1.6080144e+00
4.0293415e-01 -5.7227785e-01 9.7521200e-01
3.8960704e+00 -3.0572263e+00 6.9532967e+00
2.0293334e+00 3.8357078e+00 1.8063743e+00
-1.0605231e-01 6.8998627e-01 7.9603858e-01

**Comment by yanxon** [comment]
@weilaigit, it seems like the predicted value is equal to the negative of the true value. For some reason, ASE stress has the opposite sign than other conventional stress.

If you don't mind, can you please send me a sample of your traj (~5-10 structures) file? This way I can inspect it more thoroughly.

If so, you can send it to: hg.yanxon@gmail.com. Thank you in advance!

**Comment by weilaigit** [comment]
@yanxon ASE stress has the same sign as LAMMPS as they are both real stress.  "Stress" in vasprun.xml or OUTCAR is actually pressure but this was taken care of when converting vasprun.xml to ASE trajectory.

If I only use the 1st and 2nd structure of a 50000 structure trajectory (training2.traj), stress can be trained well but not energy or force.

The results for energy:
    Energy R2     -51.356571
    Energy MAE    0.001262
    Energy RMSE   0.001267
The energy figure is exported to: Si-so3/Energy_Train.png


The results for force:
    Force R2      -2.801335
    Force MAE     0.049863
    Force RMSE    0.085431
The force figure is exported to: Si-so3/Force_Train.png


The results for stress:
    Stress R2      0.966766
    Stress MAE     0.086745
    Stress RMSE    0.133160
The stress figure is exported to: Si-so3/Stress_Train.png

If we take the structures of 2000 and 2010 (from training3.traj), energy and force can be trained well but not stress.

The results for energy:
    Energy R2     0.872823
    Energy MAE    0.000417
    Energy RMSE   0.000582
The energy figure is exported to: Si-so3/Energy_Train.png


The results for force:
    Force R2      0.992692
    Force MAE     0.056767
    Force RMSE    0.070395
The force figure is exported to: Si-so3/Force_Train.png


The results for stress:
    Stress R2      -1.172536
    Stress MAE     0.832623
    Stress RMSE    1.028161
The stress figure is exported to: Si-so3/Stress_Train.png

I will be sending the two trajectories (training2.traj: 1&2; training3.traj: 2000, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090) through email.

**Comment by yanxon** [comment]
@weilaigit, thank you for sending me the traj files.

I believe the stress sign should be negative of the one in the traj files, and I have updated the code to accommodate this (a4207e884bf89b2bac6347e319cec4008a083f07).

Here is my training script:
```
from pyxtal_ff import PyXtal_FF
import os

TrainData = "./training3.traj"

descriptor = {'type': 'SO3',
'Rc': 5.0,
'parameters': {'lmax': 3, 'nmax': 3},
'ncpu': 1,
#'N_train': 1,
}

model = {'system' : ['Si'],
'hiddenlayers': [30, 30],
'path': 'Si-so3/',
'optimizer': {'method': 'lbfgs', 'lr': 5e-4},
'force_coefficient': 0.1,
'stress_coefficient': 2e-3,
'epoch': 20,
}

ff = PyXtal_FF(descriptors=descriptor, model=model)
ff.run(mode='train', TrainData=TrainData)
```

Result:
```
The results for energy:
    Energy R2     0.719728
    Energy MAE    0.001671
    Energy RMSE   0.001733

The results for force:
    Force R2      0.988090
    Force MAE     0.070885
    Force RMSE    0.089717

The results for stress:
    Stress R2      0.788931
    Stress MAE     0.236884
    Stress RMSE    0.283833
```

**Comment by weilaigit** [comment]
@yanxon Yes, sign change seems to fix the problem.  Thanks for the help.
