### ISSUE TITLE
SO3 spectrum 

### ISSUE THREAD

**Issue by Dong-Shiyu** [qzhu2017/PyXtal_FF#54]
1. Why the normal factors and overlaps of polynomials are different from Bartok's original ones?  
2. SO3.py[(https://github.com/qzhu2017/PyXtal_FF/blob/32cc4e7598a00a04c304e6ba15151a136d3177ca/pyxtal_ff/descriptors/SO3.py#L277)          cs = np.einsum('inlm,l->inlm', cs, norm)    why do we need to multiply this norm factor?

**Comment by qzhu2017** [comment]
Please check out our paper, we gave the reasoning in Section II.A

**Comment by Dong-Shiyu** [comment]
Sorry,after read the paper  "PyXtal_FF: a python library for automated force field generation"
I think both the paper and the code is wrong, the formula and the factor is not right.
the normal factor in this paper is     np.sqrt(2*rcut**(2*alpha+7)/(2*alpha+5)/(2*alpha+6)/(2*alpha+7))
I don't know which paper have the right information.

**Comment by qzhu2017** [comment]
https://arxiv.org/pdf/2005.04332.pdf
<img width="396" alt="image" src="https://user-images.githubusercontent.com/29445366/159026163-cd1375d1-0eeb-4322-9fc3-4ca583502fe2.png">

**Comment by Dong-Shiyu** [comment]
Get it. Thank you!
